version: '3.3'

services:
  postgres96:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'u3jollt5esm84g'
      POSTGRES_PASSWORD: 'p2e0861f4de93bf9138d27d416e8d34ff729c329c5d6924d8b0ce886dc7013675'
    ports:
      - "5432:5432"
    container_name: pg
